# Generated by Django 5.2.17 on 2026-10-05 13:59

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0005_target_binding_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("actor_uuid", models.UUIDField(null=True, blank=True)),
                ("actor_kind", models.CharField(default="system", max_length=6)),
                ("action", models.CharField(max_length=32)),
                ("result", models.CharField(max_length=12)),
                ("subject_type", models.CharField(default="account", max_length=16)),
                ("subject_uuid", models.UUIDField(null=True, blank=True)),
                ("correlation_id", models.UUIDField()),
                ("reason_code", models.CharField(blank=True, max_length=32)),
                ("changed_fields", models.JSONField(default=list, blank=True)),
                ("at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["subject_uuid", "at"], name="audit_subject_time"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "action__in",
                                (
                                    "otp.requested",
                                    "otp.delivery",
                                    "otp.verification",
                                    "account.login",
                                    "account.logout",
                                    "account.logout_all",
                                    "account.state_changed",
                                    "account.phone_changed",
                                    "recovery.requested",
                                    "recovery.assigned",
                                    "recovery.evidence",
                                    "recovery.approved",
                                    "recovery.rejected",
                                    "recovery.applied",
                                    "phone_change.requested",
                                    "consent.granted",
                                    "consent.revoked",
                                    "feature_flag.changed",
                                    "referral.created",
                                    "referral.attributed",
                                    "privacy.intake",
                                    "privacy.hold",
                                    "privacy.policy",
                                    "outbox.retry",
                                    "staff.step_up",
                                    "staff.capability",
                                ),
                            )
                        ),
                        name="audit_action",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "result__in",
                                (
                                    "accepted",
                                    "denied",
                                    "failed",
                                    "succeeded",
                                    "throttled",
                                    "unavailable",
                                ),
                            )
                        ),
                        name="audit_result",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("actor_kind__in", ["system", "user", "job"])
                        ),
                        name="audit_actor_kind",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "subject_type__in",
                                [
                                    "account",
                                    "recovery",
                                    "consent",
                                    "privacy",
                                    "flag",
                                    "outbox",
                                    "referral",
                                    "staff",
                                ],
                            )
                        ),
                        name="audit_subject_type",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "reason_code__in",
                                (
                                    "",
                                    "account_ineligible",
                                    "adult_required",
                                    "case_conflict",
                                    "cooldown",
                                    "delivery_accepted",
                                    "delivery_failed",
                                    "hold_applied",
                                    "hold_released",
                                    "identity_verified",
                                    "invalid_proof",
                                    "operator_retry",
                                    "permission_denied",
                                    "phone_conflict",
                                    "policy_approved",
                                    "quota_exceeded",
                                    "receipt_expired",
                                    "security_restriction",
                                    "staff_assigned",
                                    "user_requested",
                                    "valid_proof",
                                ),
                            )
                        ),
                        name="audit_reason_code",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(max_length=32)),
                ("schema_version", models.PositiveSmallIntegerField(default=1)),
                ("aggregate_uuid", models.UUIDField()),
                ("aggregate_version", models.PositiveBigIntegerField()),
                ("payload", models.JSONField(default=dict)),
                ("dedup_key", models.CharField(max_length=160, unique=True)),
                ("state", models.CharField(default="pending", max_length=9)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "available_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("lease_until", models.DateTimeField(null=True)),
                ("lease_uuid", models.UUIDField(null=True)),
                ("dispatched_at", models.DateTimeField(null=True)),
                ("exhausted_at", models.DateTimeField(null=True)),
                ("last_error_code", models.CharField(blank=True, max_length=32)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["state", "available_at", "lease_until"],
                        name="outbox_due_lease",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "event_type__in",
                                (
                                    "account.security_changed",
                                    "consent.revoked",
                                    "privacy.intake_recorded",
                                    "feature_flag.changed",
                                ),
                            )
                        ),
                        name="outbox_type",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("schema_version", 1)),
                        name="outbox_schema_version",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("aggregate_version__gte", 1)),
                        name="outbox_aggregate_version",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("state__in", ["pending", "leased", "sent", "exhausted"])
                        ),
                        name="outbox_state",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("attempts__lte", 8)),
                        name="outbox_attempt_bound",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("lease_until__isnull", True),
                                ("lease_uuid__isnull", True),
                            ),
                            models.Q(
                                ("lease_until__isnull", False),
                                ("lease_uuid__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="outbox_lease_pair",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StaffCapabilityGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("capability", models.CharField(max_length=24)),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_until", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(null=True)),
                ("reason_code", models.CharField(max_length=32)),
                (
                    "granted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_staff_capabilities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_capabilities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("revoked_at__isnull", True)),
                        fields=("user", "capability"),
                        name="staff_live_capability",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "capability__in",
                                (
                                    "account_recovery",
                                    "account_restriction",
                                    "security_audit",
                                    "privacy_operations",
                                    "feature_flags",
                                ),
                            )
                        ),
                        name="staff_capability_kind",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("valid_until__gt", models.F("valid_from"))),
                        name="staff_capability_expiry",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StaffStepUpGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("auth_version", models.PositiveBigIntegerField()),
                ("capability", models.CharField(max_length=24)),
                ("case_uuid", models.UUIDField(null=True)),
                ("method", models.CharField(max_length=16)),
                ("provider_reference", models.UUIDField(unique=True)),
                (
                    "verified_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(null=True)),
                (
                    "trusted_issuer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_staff_step_ups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_step_ups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "capability__in",
                                (
                                    "account_recovery",
                                    "account_restriction",
                                    "security_audit",
                                    "privacy_operations",
                                    "feature_flags",
                                ),
                            )
                        ),
                        name="step_up_capability_kind",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("auth_version__gte", 1)),
                        name="step_up_auth_version",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("expires_at__gt", models.F("verified_at"))),
                        name="step_up_expiry",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("method__in", ["mock", "verified_mfa"])),
                        name="step_up_method",
                    ),
                ],
            },
        ),
    ]
