# Generated by Django 5.2.17 on 2026-10-05 19:45

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("governance", "0003_evidence_payload_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Consent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("purpose", models.CharField(max_length=32)),
                ("text_version", models.CharField(max_length=64)),
                ("content_hash", models.CharField(max_length=64)),
                ("granted_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(null=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                (
                    "grantee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConsentScope",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(max_length=32)),
                ("object_uuid", models.UUIDField()),
                ("object_version", models.PositiveBigIntegerField()),
                (
                    "consent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scopes",
                        to="governance.consent",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="consent",
            index=models.Index(
                fields=["subject", "grantee", "purpose"],
                name="consent_exact_participants",
            ),
        ),
        migrations.AddConstraint(
            model_name="consent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "purpose__in",
                        (
                            "account_metadata",
                            "active_sharing",
                            "archive_sharing",
                            "nutrition_adherence_read",
                            "ai_feature",
                            "mirror_summary",
                            "case_study",
                        ),
                    )
                ),
                name="consent_purpose",
            ),
        ),
        migrations.AddConstraint(
            model_name="consent",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)), name="consent_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="consent",
            constraint=models.CheckConstraint(
                condition=models.Q(("expires_at__gt", models.F("granted_at"))),
                name="consent_expiry",
            ),
        ),
        migrations.AddConstraint(
            model_name="consent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("revoked_at__isnull", True),
                    ("revoked_at__gte", models.F("granted_at")),
                    _connector="OR",
                ),
                name="consent_revocation_time",
            ),
        ),
        migrations.AddConstraint(
            model_name="consent",
            constraint=models.CheckConstraint(
                condition=models.Q(("content_hash__regex", "^[0-9a-f]{64}$")),
                name="consent_content_hash",
            ),
        ),
        migrations.AddConstraint(
            model_name="consent",
            constraint=models.CheckConstraint(
                condition=models.Q(("text_version__regex", "^[a-zA-Z0-9_.:-]{1,64}$")),
                name="consent_text_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="consentscope",
            constraint=models.CheckConstraint(
                condition=models.Q(("object_version__gte", 1)),
                name="consent_scope_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="consentscope",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__regex", "^[a-z_]{1,32}$")),
                name="consent_scope_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="consentscope",
            constraint=models.UniqueConstraint(
                fields=("consent", "kind", "object_uuid", "object_version"),
                name="consent_scope_unique",
            ),
        ),
    ]
