# Generated by Django 5.2.17 on 2026-10-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("governance", "0004_consent_core"),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION fitlink_valid_outbox_payload(
                kind text, value jsonb)
            RETURNS boolean LANGUAGE plpgsql IMMUTABLE STRICT AS $$
            DECLARE
                allowed text[];
                item record;
            BEGIN
                IF jsonb_typeof(value) <> 'object' THEN RETURN false; END IF;
                allowed := CASE kind
                    WHEN 'account.security_changed' THEN ARRAY['user_uuid']
                    WHEN 'consent.granted' THEN ARRAY['consent_uuid','user_uuid']
                    WHEN 'consent.revoked' THEN ARRAY['consent_uuid','user_uuid']
                    WHEN 'privacy.intake_recorded'
                        THEN ARRAY['privacy_uuid','user_uuid']
                    WHEN 'feature_flag.changed' THEN ARRAY['flag_uuid']
                    ELSE NULL END;
                IF allowed IS NULL THEN RETURN false; END IF;
                FOR item IN SELECT * FROM jsonb_each(value) LOOP
                    IF NOT (item.key = ANY(allowed)) OR
                       jsonb_typeof(item.value) <> 'string' OR
                       (item.value #>> '{}') !~
                       '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
                    THEN RETURN false; END IF;
                END LOOP;
                RETURN true;
            END;
            $$;
            """,
            migrations.RunSQL.noop,
        ),
        migrations.RemoveConstraint(
            model_name="outboxevent",
            name="outbox_type",
        ),
        migrations.AddConstraint(
            model_name="outboxevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "event_type__in",
                        (
                            "account.security_changed",
                            "consent.granted",
                            "consent.revoked",
                            "privacy.intake_recorded",
                            "feature_flag.changed",
                        ),
                    )
                ),
                name="outbox_type",
            ),
        ),
    ]
