# Generated by Django 5.2.17 on 2026-10-05 20:24

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("governance", "0006_consent_terminal_guards"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=32, unique=True)),
                ("enabled", models.BooleanField(default=False)),
                ("version", models.PositiveBigIntegerField(default=1)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "key__in",
                                (
                                    "marketplace",
                                    "professional_registration",
                                    "ai_insights",
                                    "ai_mirror",
                                ),
                            )
                        ),
                        name="feature_key",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)), name="feature_version"
                    ),
                ],
            },
        ),
    ]
