# Generated by Django 5.2.17 on 2026-10-05 22:14

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("governance", "0008_seed_feature_flags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivacyRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(max_length=6)),
                ("status", models.CharField(max_length=20)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("created_at", models.DateTimeField()),
                ("verified_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("kind__in", ["export", "delete"])),
                        name="privacy_kind",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("kind", "export"), ("status", "pending_execution")
                            ),
                            models.Q(
                                ("kind", "delete"), ("status", "pending_deletion")
                            ),
                            _connector="OR",
                        ),
                        name="privacy_intake_status",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)), name="privacy_version"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("verified_at__gte", models.F("created_at"))
                        ),
                        name="privacy_verified_time",
                    ),
                    models.UniqueConstraint(
                        fields=("user", "kind"), name="privacy_open_kind"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RecordHold",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject_kind", models.CharField(max_length=32)),
                ("subject_uuid", models.UUIDField()),
                ("subject_version", models.PositiveBigIntegerField()),
                ("owner_uuid", models.UUIDField()),
                ("case_uuid", models.UUIDField()),
                ("purpose", models.CharField(max_length=16)),
                ("reason_code", models.CharField(max_length=32)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("review_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("released_at", models.DateTimeField(null=True)),
                (
                    "authorized_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("subject_kind", "privacy_request")),
                        name="hold_subject_kind",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "purpose__in",
                                ["dispute", "fraud", "security", "required_audit"],
                            )
                        ),
                        name="hold_purpose",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("subject_version__gte", 1), ("version__gte", 1)
                        ),
                        name="hold_versions",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("expires_at__gte", models.F("review_at")),
                            ("review_at__gt", models.F("created_at")),
                        ),
                        name="hold_review_expiry",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("released_at__isnull", True),
                            ("released_at__gte", models.F("created_at")),
                            _connector="OR",
                        ),
                        name="hold_release_time",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RetentionPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data_class", models.CharField(max_length=32)),
                ("purpose", models.CharField(max_length=32)),
                ("status", models.CharField(default="draft", max_length=12)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("duration_seconds", models.PositiveBigIntegerField(null=True)),
                ("backup_reference", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("approved_at", models.DateTimeField(null=True)),
                ("effective_at", models.DateTimeField(null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                ["draft", "approved", "effective", "superseded"],
                            )
                        ),
                        name="retention_status",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="retention_version",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("duration_seconds__isnull", True),
                            ("duration_seconds__gt", 0),
                            _connector="OR",
                        ),
                        name="retention_duration",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status", "draft"),
                            models.Q(
                                ("approved_at__isnull", False),
                                ("approved_by__isnull", False),
                                ("duration_seconds__isnull", False),
                                models.Q(("backup_reference", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="retention_approval",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "effective"), _negated=True),
                            ("effective_at__isnull", False),
                            _connector="OR",
                        ),
                        name="retention_effective",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "effective")),
                        fields=("data_class", "purpose"),
                        name="retention_one_effective",
                    ),
                ],
            },
        ),
    ]
