# Generated by Django 5.2.17 on 2026-10-06 03:32

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("governance", "0009_privacyrequest_recordhold_retentionpolicy"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboxDeliveryReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("handler", models.CharField(max_length=32)),
                ("effect_key", models.CharField(max_length=120)),
                ("result", models.CharField(max_length=7)),
                ("completed_at", models.DateTimeField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipts",
                        to="governance.outboxevent",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("handler", "effect_key"), name="outbox_durable_effect"
                    ),
                    models.UniqueConstraint(
                        fields=("event", "handler"), name="outbox_event_handler"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("result__in", ["applied", "skipped"])),
                        name="outbox_receipt_result",
                    ),
                ],
            },
        ),
    ]
