# Generated by Django 5.2.17 on 2026-10-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("governance", "0013_c03_audit_consent_hold_contracts"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="auditevent",
            name="audit_action",
        ),
        migrations.AddConstraint(
            model_name="auditevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "action__in",
                        (
                            "otp.requested",
                            "otp.delivery",
                            "otp.verification",
                            "account.login",
                            "account.logout",
                            "account.logout_all",
                            "account.state_changed",
                            "account.phone_changed",
                            "recovery.requested",
                            "recovery.assigned",
                            "recovery.evidence",
                            "recovery.approved",
                            "recovery.rejected",
                            "recovery.applied",
                            "phone_change.requested",
                            "consent.granted",
                            "consent.revoked",
                            "feature_flag.changed",
                            "referral.created",
                            "referral.attributed",
                            "privacy.intake",
                            "privacy.hold",
                            "privacy.policy",
                            "outbox.retry",
                            "staff.step_up",
                            "staff.capability",
                            "athlete.profile_created",
                            "baseline.saved",
                            "baseline.submitted",
                            "baseline.corrected",
                            "baseline.cleared",
                            "baseline.read",
                            "professional.profile_created",
                            "professional.profile_saved",
                            "professional.roles_changed",
                            "credential.created",
                            "credential.revised",
                            "credential.withdrawn",
                            "asset.begun",
                            "asset.uploaded",
                            "asset.finalized",
                            "asset.read",
                            "asset.rejected",
                            "asset.revoked",
                            "asset.deleted",
                            "verification.submitted",
                            "verification.assigned",
                            "verification.review_started",
                            "verification.read",
                            "verification.approved",
                            "verification.rejected",
                            "verification.stale",
                            "verification.withdrawn",
                            "verification.revoked",
                            "professional.role_restricted",
                            "professional.role_released",
                            "assistant.defined",
                            "assistant.revoked",
                        ),
                    )
                ),
                name="audit_action",
            ),
        ),
    ]
