# Generated by Django 5.2.17 on 2026-10-05 13:36

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.accounts.security_models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="adult_attestation_version",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="user",
            name="adult_attested_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="auth_version",
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="locale",
            field=models.CharField(default="fa", max_length=5),
        ),
        migrations.AddField(
            model_name="user",
            name="state",
            field=models.CharField(default="active", max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="state_version",
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="user",
            name="timezone",
            field=models.CharField(default="Asia/Tehran", max_length=64),
        ),
        migrations.CreateModel(
            name="OTPPhoneState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=13, unique=True)),
                ("generation", models.PositiveBigIntegerField(default=0)),
                (
                    "next_send_at",
                    models.DateTimeField(
                        default=apps.accounts.security_models.never_sent
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("phone__regex", "^\\+989[0-9]{9}$")),
                        name="otp_phone_canonical",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("generation__gte", 0)),
                        name="otp_generation_nonnegative",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityRateAnchor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("phone", "phone"), ("ip", "ip")], max_length=5
                    ),
                ),
                ("key_id", models.CharField(max_length=32)),
                ("key_digest", models.CharField(max_length=64)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "key_id", "key_digest"),
                        name="rate_anchor_identity",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("kind__in", ["phone", "ip"])),
                        name="rate_anchor_kind",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("key_id__regex", "^[A-Za-z0-9_-]{1,32}$")),
                        name="rate_anchor_key_id",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("key_digest__regex", "^[0-9a-f]{64}$")),
                        name="rate_anchor_digest",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AccountSessionControl",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key_id", models.CharField(max_length=32)),
                ("session_digest", models.CharField(max_length=64)),
                ("auth_version", models.PositiveBigIntegerField()),
                ("scope", models.CharField(max_length=15)),
                ("authenticated_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "revoked_at", "expires_at"], name="session_live"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("key_id", "session_digest"),
                        name="session_control_digest",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("key_id__regex", "^[A-Za-z0-9_-]{1,32}$")),
                        name="session_control_key_id",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("session_digest__regex", "^[0-9a-f]{64}$")),
                        name="session_control_hmac",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("auth_version__gte", 1)),
                        name="session_auth_version",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("scope__in", ["normal", "account_control"])
                        ),
                        name="session_scope",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("expires_at__gt", models.F("created_at"))),
                        name="session_expiry",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OTPChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("generation", models.PositiveBigIntegerField()),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("login", "login"),
                            ("recovery_new_phone", "recovery_new_phone"),
                            ("phone_change_old", "phone_change_old"),
                            ("phone_change_new", "phone_change_new"),
                        ],
                        max_length=18,
                    ),
                ),
                (
                    "context_uuid",
                    models.UUIDField(
                        default=uuid.UUID("00000000-0000-0000-0000-000000000000")
                    ),
                ),
                ("target_auth_version", models.PositiveBigIntegerField(null=True)),
                ("key_id", models.CharField(max_length=32)),
                ("code_digest", models.CharField(max_length=64)),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                ("delivery_state", models.CharField(default="pending", max_length=7)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("consumed_at", models.DateTimeField(null=True)),
                ("proof_applied_at", models.DateTimeField(null=True)),
                ("locked_at", models.DateTimeField(null=True)),
                ("retired_at", models.DateTimeField(null=True)),
                (
                    "target_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "phone_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.otpphonestate",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["phone_state", "purpose", "issued_at"],
                        name="otp_phone_purpose",
                    ),
                    models.Index(fields=["expires_at"], name="otp_expiry"),
                    models.Index(
                        fields=["target_user", "target_auth_version"],
                        name="otp_bound_identity",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("phone_state", "generation", "purpose", "context_uuid"),
                        name="otp_generation_context",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "purpose__in",
                                (
                                    "login",
                                    "recovery_new_phone",
                                    "phone_change_old",
                                    "phone_change_new",
                                ),
                            )
                        ),
                        name="otp_purpose",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("delivery_state__in", ["pending", "sent", "failed"])
                        ),
                        name="otp_delivery_state",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("generation__gte", 1)),
                        name="otp_generation_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("attempts__lte", 5)),
                        name="otp_attempts_bound",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("expires_at__gt", models.F("issued_at"))),
                        name="otp_expiry_after_issue",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("key_id__regex", "^[A-Za-z0-9_-]{1,32}$")),
                        name="otp_key_id",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("code_digest__regex", "^[0-9a-f]{64}$")),
                        name="otp_code_digest",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                (
                                    "context_uuid",
                                    uuid.UUID("00000000-0000-0000-0000-000000000000"),
                                ),
                                ("purpose", "login"),
                            ),
                            models.Q(
                                models.Q(("purpose", "login"), _negated=True),
                                models.Q(
                                    (
                                        "context_uuid",
                                        uuid.UUID(
                                            "00000000-0000-0000-0000-000000000000"
                                        ),
                                    ),
                                    _negated=True,
                                ),
                            ),
                            _connector="OR",
                        ),
                        name="otp_purpose_context",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("target_auth_version__isnull", True),
                                ("target_user__isnull", True),
                            ),
                            models.Q(
                                ("target_auth_version__gte", 1),
                                ("target_user__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="otp_target_version",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("consumed_at__isnull", True),
                            models.Q(
                                ("consumed_at__gte", models.F("issued_at")),
                                ("consumed_at__lt", models.F("expires_at")),
                                ("delivery_state", "sent"),
                                ("locked_at__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="otp_consumed_consistency",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("proof_applied_at__isnull", True),
                            models.Q(
                                ("consumed_at__isnull", False),
                                models.Q(("purpose", "login"), _negated=True),
                                ("proof_applied_at__gte", models.F("consumed_at")),
                            ),
                            _connector="OR",
                        ),
                        name="otp_applied_proof",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityRateEvent",
            fields=[
                (
                    "reservation_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(max_length=16)),
                ("outcome", models.CharField(default="pending", max_length=9)),
                ("at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "ip_anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ip_events",
                        to="accounts.securityrateanchor",
                    ),
                ),
                (
                    "phone_anchor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phone_events",
                        to="accounts.securityrateanchor",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["phone_anchor", "kind", "at"], name="rate_phone_window"
                    ),
                    models.Index(
                        fields=["ip_anchor", "kind", "at"], name="rate_ip_window"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("kind__in", ["send", "verify_failure", "recovery_intake"])
                        ),
                        name="rate_event_kind",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("outcome__in", ["pending", "failed", "succeeded"])
                        ),
                        name="rate_event_outcome",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("phone_anchor", models.F("ip_anchor")), _negated=True
                        ),
                        name="rate_event_distinct_anchors",
                    ),
                ],
            },
        ),
    ]
