# Generated by Django 5.2.17 on 2026-10-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_map_legacy_account_state"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("auth_version__gte", 1)),
                name="account_auth_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("state_version__gte", 1)),
                name="account_state_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("is_active", True),
                        (
                            "state__in",
                            [
                                "active",
                                "restricted",
                                "deletion_requested",
                                "pending_deletion",
                            ],
                        ),
                    ),
                    models.Q(
                        ("is_active", False),
                        (
                            "state__in",
                            [
                                "suspended",
                                "deleted",
                                "anonymized",
                                "deletion_completed",
                            ],
                        ),
                    ),
                    _connector="OR",
                ),
                name="account_state_active_consistency",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("adult_attestation_version", ""),
                        ("adult_attested_at__isnull", True),
                    ),
                    models.Q(
                        ("adult_attested_at__isnull", False),
                        ("birth_date__isnull", False),
                        models.Q(("adult_attestation_version", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="account_attestation_consistency",
            ),
        ),
    ]
