# Generated by Django 5.2.17 on 2026-10-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_account_state_constraints"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="otpchallenge",
            name="otp_target_version",
        ),
        migrations.AddConstraint(
            model_name="otpchallenge",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("target_auth_version__isnull", True),
                        ("target_user__isnull", True),
                    ),
                    models.Q(
                        ("target_auth_version__gte", 1),
                        ("target_auth_version__isnull", False),
                        ("target_user__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="otp_target_version",
            ),
        ),
    ]
