# Generated by Django 5.2.17 on 2026-10-05 18:00

import uuid

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_target_binding_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecoveryRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("claimed_old_phone", models.CharField(max_length=13)),
                ("proposed_new_phone", models.CharField(max_length=13)),
                (
                    "contact_preference",
                    models.CharField(default="new_phone", max_length=9),
                ),
                ("target_auth_version", models.PositiveBigIntegerField(null=True)),
                ("state", models.CharField(default="received", max_length=8)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("receipt_key_id", models.CharField(max_length=32)),
                ("receipt_digest", models.CharField(max_length=64, unique=True)),
                ("receipt_expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("decision_reason", models.CharField(default="", max_length=32)),
                (
                    "evidence_decision",
                    models.CharField(default="unresolved", max_length=10),
                ),
                ("new_phone_verified_at", models.DateTimeField(null=True)),
                ("applied_at", models.DateTimeField(null=True)),
                ("effect_auth_version", models.PositiveBigIntegerField(null=True)),
                (
                    "assigned_staff",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_recoveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decision_authorizer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recovery_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "new_phone_challenge",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recovery_proofs",
                        to="accounts.otpchallenge",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recovery_targets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecoveryEvidenceMetadata",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("classification", models.CharField(max_length=15)),
                ("outcome", models.CharField(max_length=10)),
                ("checksum", models.CharField(max_length=64)),
                ("secured_reference", models.UUIDField()),
                (
                    "reviewed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recovery_evidence_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence",
                        to="accounts.recoveryrequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PhoneChangeHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("old_phone", models.CharField(max_length=13)),
                ("new_phone", models.CharField(max_length=13)),
                ("recovery_context", models.UUIDField(null=True, unique=True)),
                ("change_context", models.UUIDField(null=True, unique=True)),
                ("actor_uuid", models.UUIDField()),
                ("at", models.DateTimeField(default=django.utils.timezone.now)),
                ("old_auth_version", models.PositiveBigIntegerField()),
                ("new_auth_version", models.PositiveBigIntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phone_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("new_phone__regex", "^\\+989[0-9]{9}$"),
                            ("old_phone__regex", "^\\+989[0-9]{9}$"),
                            models.Q(
                                ("old_phone", models.F("new_phone")), _negated=True
                            ),
                        ),
                        name="history_distinct_phones",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("change_context__isnull", True),
                                ("recovery_context__isnull", False),
                            ),
                            models.Q(
                                ("change_context__isnull", False),
                                ("recovery_context__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="history_exact_context",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "new_auth_version",
                                django.db.models.expressions.CombinedExpression(
                                    models.F("old_auth_version"), "+", models.Value(1)
                                ),
                            ),
                            ("old_auth_version__gte", 1),
                        ),
                        name="history_auth_versions",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="recoveryrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("claimed_old_phone__regex", "^\\+989[0-9]{9}$"),
                    ("proposed_new_phone__regex", "^\\+989[0-9]{9}$"),
                    models.Q(
                        ("claimed_old_phone", models.F("proposed_new_phone")),
                        _negated=True,
                    ),
                ),
                name="recovery_distinct_phones",
            ),
        ),
        migrations.AddConstraint(
            model_name="recoveryrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("contact_preference", "new_phone")),
                name="recovery_contact_preference",
            ),
        ),
        migrations.AddConstraint(
            model_name="recoveryrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="recovery_positive_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="recoveryrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("state__in", ["received", "approved", "rejected", "applied"])
                ),
                name="recovery_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="recoveryrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("receipt_digest__regex", "^[0-9a-f]{64}$"),
                    ("receipt_expires_at__gt", models.F("created_at")),
                    ("receipt_key_id__regex", "^[A-Za-z0-9_-]{1,32}$"),
                ),
                name="recovery_receipt",
            ),
        ),
        migrations.AddConstraint(
            model_name="recoveryrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("target_auth_version__isnull", True),
                        ("target_user__isnull", True),
                    ),
                    models.Q(
                        ("target_auth_version__gte", 1),
                        ("target_auth_version__isnull", False),
                        ("target_user__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="recovery_target_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="recoveryrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("new_phone_challenge__isnull", True),
                        ("new_phone_verified_at__isnull", True),
                    ),
                    models.Q(
                        ("new_phone_challenge__isnull", False),
                        ("new_phone_verified_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="recovery_proof_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="recoveryrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("evidence_decision__in", ("verified", "unresolved", "rejected"))
                ),
                name="recovery_evidence_outcome",
            ),
        ),
        migrations.AddConstraint(
            model_name="recoveryrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("decision_authorizer__isnull", True),
                        ("decision_reason", ""),
                        ("state", "received"),
                    ),
                    models.Q(
                        ("decision_authorizer__isnull", False),
                        (
                            "decision_reason__in",
                            ["identity_verified", "permission_denied"],
                        ),
                        ("state__in", ["approved", "rejected", "applied"]),
                    ),
                    _connector="OR",
                ),
                name="recovery_decision_binding",
            ),
        ),
        migrations.AddConstraint(
            model_name="recoveryrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("applied_at__isnull", False),
                        ("effect_auth_version__gte", 2),
                        ("effect_auth_version__isnull", False),
                        ("new_phone_challenge__isnull", False),
                        ("state", "applied"),
                        ("target_user__isnull", False),
                    ),
                    models.Q(
                        models.Q(("state", "applied"), _negated=True),
                        ("applied_at__isnull", True),
                        ("effect_auth_version__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="recovery_effect_binding",
            ),
        ),
        migrations.AddConstraint(
            model_name="recoveryevidencemetadata",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("checksum__regex", "^[0-9a-f]{64}$"),
                    (
                        "classification__in",
                        ("identity_match", "phone_loss", "ownership_review"),
                    ),
                    ("outcome__in", ("verified", "unresolved", "rejected")),
                ),
                name="recovery_evidence_metadata",
            ),
        ),
    ]
