# Generated by Django 5.2.17 on 2026-10-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_recoveryrequest_recoveryevidencemetadata_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="recoveryrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("state__in", ["received", "approved"]),
                    ("target_user__isnull", False),
                ),
                fields=("target_user",),
                name="recovery_live_target",
            ),
        ),
    ]
