# Generated by Django 5.2.17 on 2026-10-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_history_append_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="recoveryrequest",
            name="decided_at",
            field=models.DateTimeField(null=True),
        ),
    ]
