# Generated by Django 5.2.17 on 2026-10-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_remove_recoveryrequest_recovery_decision_binding_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recoveryevidencemetadata",
            name="classification",
            field=models.CharField(max_length=16),
        ),
    ]
