# Generated by Django 5.2.17 on 2026-10-05 18:20

import uuid

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_alter_recoveryevidencemetadata_classification"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneChangeIntent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("old_phone", models.CharField(max_length=13)),
                ("new_phone", models.CharField(max_length=13)),
                ("issued_auth_version", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("old_phone_verified_at", models.DateTimeField(null=True)),
                ("new_phone_verified_at", models.DateTimeField(null=True)),
                ("applied_at", models.DateTimeField(null=True)),
                ("retired_at", models.DateTimeField(null=True)),
                ("effect_auth_version", models.PositiveBigIntegerField(null=True)),
                (
                    "new_phone_challenge",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="new_phone_intents",
                        to="accounts.otpchallenge",
                    ),
                ),
                (
                    "old_phone_challenge",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="old_phone_intents",
                        to="accounts.otpchallenge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phone_change_intents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("applied_at__isnull", True), ("retired_at__isnull", True)
                        ),
                        fields=("user",),
                        name="phone_change_live_user",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("new_phone__regex", "^\\+989[0-9]{9}$"),
                            ("old_phone__regex", "^\\+989[0-9]{9}$"),
                            models.Q(
                                ("old_phone", models.F("new_phone")), _negated=True
                            ),
                        ),
                        name="phone_change_distinct_phones",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("expires_at__gt", models.F("created_at")),
                            ("issued_auth_version__gte", 1),
                            ("version__gte", 1),
                        ),
                        name="phone_change_version_expiry",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("old_phone_challenge__isnull", True),
                                ("old_phone_verified_at__isnull", True),
                            ),
                            models.Q(
                                ("old_phone_challenge__isnull", False),
                                ("old_phone_verified_at__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="phone_change_old_proof_pair",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("new_phone_challenge__isnull", True),
                                ("new_phone_verified_at__isnull", True),
                            ),
                            models.Q(
                                ("new_phone_challenge__isnull", False),
                                ("new_phone_verified_at__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="phone_change_new_proof_pair",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("old_phone_challenge__isnull", True),
                            ("new_phone_challenge__isnull", True),
                            models.Q(
                                (
                                    "old_phone_challenge",
                                    models.F("new_phone_challenge"),
                                ),
                                _negated=True,
                            ),
                            _connector="OR",
                        ),
                        name="phone_change_distinct_proofs",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("applied_at__isnull", True),
                                ("effect_auth_version__isnull", True),
                            ),
                            models.Q(
                                ("applied_at__isnull", False),
                                (
                                    "effect_auth_version",
                                    django.db.models.expressions.CombinedExpression(
                                        models.F("issued_auth_version"),
                                        "+",
                                        models.Value(1),
                                    ),
                                ),
                                ("effect_auth_version__isnull", False),
                                ("new_phone_challenge__isnull", False),
                                ("old_phone_challenge__isnull", False),
                                ("retired_at__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="phone_change_effect_binding",
                    ),
                ],
            },
        ),
    ]
