# Generated by Django 5.2.17 on 2026-10-05 20:24

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_phonechangeintent"),
    ]

    operations = [
        migrations.CreateModel(
            name="InviteReferralLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token_digest", models.CharField(max_length=64, unique=True)),
                ("key_id", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(null=True)),
                (
                    "issuer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReferralAttribution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("attributed_at", models.DateTimeField()),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.invitereferrallink",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="invitereferrallink",
            constraint=models.CheckConstraint(
                condition=models.Q(("token_digest__regex", "^[0-9a-f]{64}$")),
                name="referral_digest",
            ),
        ),
        migrations.AddConstraint(
            model_name="invitereferrallink",
            constraint=models.CheckConstraint(
                condition=models.Q(("key_id__regex", "^[A-Za-z0-9_-]{1,32}$")),
                name="referral_key_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="invitereferrallink",
            constraint=models.CheckConstraint(
                condition=models.Q(("expires_at__gt", models.F("created_at"))),
                name="referral_expiry",
            ),
        ),
        migrations.AddConstraint(
            model_name="invitereferrallink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("revoked_at__isnull", True),
                    ("revoked_at__gte", models.F("created_at")),
                    _connector="OR",
                ),
                name="referral_revocation",
            ),
        ),
        migrations.AddConstraint(
            model_name="referralattribution",
            constraint=models.UniqueConstraint(
                fields=("recipient",), name="referral_first_attribution"
            ),
        ),
    ]
