# Generated by Django 5.2.17 on 2026-10-07 16:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0003_bounded_metadata"),
        ("professionals", "0007_assistant_nonself"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="professionalprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("experience_years__isnull", True),
                    ("experience_years__lte", 80),
                    _connector="OR",
                ),
                name="professional_experience_bound",
            ),
        ),
        migrations.AddConstraint(
            model_name="professionalprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("accent_color", ""),
                    ("accent_color__regex", "^#[0-9A-Fa-f]{6}$"),
                    _connector="OR",
                ),
                name="professional_accent_color",
            ),
        ),
        migrations.AddConstraint(
            model_name="professionalprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "setup_step__in",
                        [
                            "identity",
                            "description",
                            "locations",
                            "branding",
                            "credentials",
                            "preview",
                        ],
                    )
                ),
                name="professional_setup_step",
            ),
        ),
    ]
