# Generated by Django 5.2.17 on 2026-10-07 21:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0003_bounded_metadata"),
        ("professionals", "0008_bounded_metadata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="credentialrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_sha256__regex", "^[0-9a-f]{64}$")),
                name="credential_revision_source_hash",
            ),
        ),
        migrations.AddConstraint(
            model_name="credentialrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision_hash__regex", "^[0-9a-f]{64}$")),
                name="credential_revision_hash",
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationdecision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "reason_code__in",
                        (
                            "identity_verified",
                            "staff_assigned",
                            "user_requested",
                            "case_conflict",
                            "verification_submitted",
                            "verification_review",
                            "credentials_approved",
                            "evidence_incomplete",
                            "credentials_invalid",
                            "evidence_expired",
                            "evidence_revoked",
                            "role_restricted",
                            "restriction_removed",
                            "material_changed",
                            "owner_withdrawn",
                        ),
                    )
                ),
                name="decision_reason_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationdecision",
            constraint=models.CheckConstraint(
                condition=models.Q(("target_snapshot_hash__regex", "^[0-9a-f]{64}$")),
                name="decision_snapshot_hash",
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationhistory",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "reason_code__in",
                        (
                            "identity_verified",
                            "staff_assigned",
                            "user_requested",
                            "case_conflict",
                            "verification_submitted",
                            "verification_review",
                            "credentials_approved",
                            "evidence_incomplete",
                            "credentials_invalid",
                            "evidence_expired",
                            "evidence_revoked",
                            "role_restricted",
                            "restriction_removed",
                            "material_changed",
                            "owner_withdrawn",
                        ),
                    )
                ),
                name="verification_history_reason",
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationhistory",
            constraint=models.CheckConstraint(
                condition=models.Q(("new_version__gt", models.F("prior_version"))),
                name="verification_history_forward",
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationhistory",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("event__in", ["submit", "assign", "start_review", "reassign"]),
                    ("target__isnull", False),
                    _connector="OR",
                ),
                name="verification_history_target",
            ),
        ),
    ]
