# Generated by Django 5.2.17 on 2026-10-07 22:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("professionals", "0010_decision_snapshot_guard"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="professionalrolerestriction",
            constraint=models.CheckConstraint(
                condition=models.Q(("reason_code", "role_restricted")),
                name="role_restriction_reason",
            ),
        ),
        migrations.AddConstraint(
            model_name="professionalrolerestriction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("released_at__isnull", True),
                    ("released_at__gte", models.F("applied_at")),
                    _connector="OR",
                ),
                name="role_restriction_time",
            ),
        ),
        migrations.AddConstraint(
            model_name="profilecommandreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "command__in",
                        [
                            "profile.create",
                            "profile.save_step",
                            "credential.create",
                            "credential.revise",
                            "credential.withdraw",
                            "verification.prepare",
                            "verification.submit",
                            "verification.withdraw_target",
                            "verification.decide_target",
                            "verification.revoke_target",
                            "role.restrict",
                            "role.release_restriction",
                            "assistant.define",
                            "assistant.revoke",
                        ],
                    )
                ),
                name="professionals_receipt_command",
            ),
        ),
        migrations.AddConstraint(
            model_name="profilecommandreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(("request_hash__regex", "^[0-9a-f]{64}$")),
                name="professionals_receipt_hash",
            ),
        ),
        migrations.AddConstraint(
            model_name="rolerestrictionhistory",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reason_code__in", ["role_restricted", "restriction_removed"])
                ),
                name="restriction_history_reason",
            ),
        ),
        migrations.AddConstraint(
            model_name="rolerestrictionhistory",
            constraint=models.CheckConstraint(
                condition=models.Q(("new_version__gt", models.F("prior_version"))),
                name="restriction_history_forward",
            ),
        ),
    ]
