# Generated by Django 5.2.17 on 2026-10-07 22:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("professionals", "0015_lifecycle_timestamp_guards"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="assistantmembership",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("revoked_at__isnull", True), ("state", "defined")),
                    models.Q(("revoked_at__isnull", False), ("state", "revoked")),
                    _connector="OR",
                ),
                name="assistant_revocation_time",
            ),
        ),
        migrations.AddConstraint(
            model_name="verification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("state", "decided"), _negated=True),
                    ("decided_at__isnull", False),
                    _connector="OR",
                ),
                name="verification_decided_timestamp",
            ),
        ),
    ]
