Foreground yes
LogFile /dev/null
LogTime no
LogClean no
LogVerbose no
LogSyslog no
DatabaseDirectory /var/lib/clamav
TCPSocket 3310
TCPAddr 0.0.0.0
MaxThreads 2
MaxQueue 4
ReadTimeout 10
CommandReadTimeout 5
SendBufTimeout 5
StreamMaxLength 10000000
MaxScanSize 10000000
MaxFileSize 10000000
MaxScanTime 10000
MaxRecursion 2
MaxFiles 10
AlertExceedsMax yes
DetectPUA yes
ScanArchive no
ScanPDF no
ScanHTML no
ScanOLE2 no
ScanMail no
ScanPE no
ScanELF no
ScanSWF no
ScanXMLDOCS no
ScanHWP3 no
TemporaryDirectory /tmp
SelfCheck 30
