# Generated by Django 5.2.17 on 2026-10-07 16:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0002_remove_assetprocessingattempt_attempt_lease_pair_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.CheckConstraint(
                condition=models.Q(("declared_size__lte", 10000000)),
                name="asset_declared_size_cap",
            ),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("actual_size__isnull", True),
                    ("actual_size__lte", 10000000),
                    _connector="OR",
                ),
                name="asset_actual_size_cap",
            ),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("declared_type__in", ["", "image/jpeg", "image/png"])
                ),
                name="asset_declared_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("detected_type__in", ["", "image/jpeg", "image/png"])
                ),
                name="asset_detected_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sha256", ""), ("sha256__regex", "^[0-9a-f]{64}$"), _connector="OR"
                ),
                name="asset_source_hash",
            ),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "subject_kind__in",
                        ["professional_profile", "professional_credential"],
                    )
                ),
                name="asset_subject_kind",
            ),
        ),
    ]
