# Generated by Django 5.2.17 on 2026-10-07 22:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0004_immutable_accepted_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="assetderivative",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="assetderivative",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="assetprocessingattempt",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="assetprocessingattempt",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
