# Generated by Django 5.2.17 on 2026-10-07 22:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0006_lifecycle_timestamp_guard"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("state", "ready"), _negated=True),
                    models.Q(
                        ("accepted_at__isnull", False),
                        ("actual_size__gte", 1),
                        ("actual_size__isnull", False),
                        ("detected_type__in", ["image/jpeg", "image/png"]),
                        ("finalized_at__isnull", False),
                        ("sha256__regex", "^[0-9a-f]{64}$"),
                    ),
                    _connector="OR",
                ),
                name="asset_ready_metadata",
            ),
        ),
        migrations.AddConstraint(
            model_name="assetderivative",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("height__gte", 1),
                    ("height__lte", 1600),
                    ("width__gte", 1),
                    ("width__lte", 1600),
                ),
                name="derivative_dimensions_bound",
            ),
        ),
        migrations.AddConstraint(
            model_name="assetderivative",
            constraint=models.CheckConstraint(
                condition=models.Q(("sha256__regex", "^[0-9a-f]{64}$")),
                name="derivative_checksum",
            ),
        ),
        migrations.AddConstraint(
            model_name="assetprocessingattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("state", "running"), _negated=True),
                    models.Q(
                        ("lease_until__isnull", False), ("lease_uuid__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="attempt_running_lease",
            ),
        ),
    ]
