# Generated by Django 5.2.17 on 2026-10-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0007_lifecycle_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetprocessingattempt",
            name="asset_version",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="assetprocessingattempt",
            name="authority_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="assetprocessingattempt",
            name="owner_auth_version",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="assetprocessingattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("state", "running"), _negated=True),
                    models.Q(
                        ("asset_version__gte", 1),
                        ("authority_hash__regex", "^[0-9a-f]{64}$"),
                        ("owner_auth_version__gte", 1),
                    ),
                    _connector="OR",
                ),
                name="attempt_running_authority",
            ),
        ),
    ]
