# Generated by Django 5.2.17 on 2026-10-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0008_processing_authority"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetprocessingattempt",
            name="algorithm_version",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="assetprocessingattempt",
            name="prompt_attempt",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="assetprocessingattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("prompt_attempt__lte", 8)),
                name="attempt_prompt_bound",
            ),
        ),
        migrations.AddConstraint(
            model_name="assetprocessingattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("state", "running"), _negated=True),
                    models.Q(
                        ("algorithm_version", "jpeg-png-pixels-v1"),
                        ("prompt_attempt__gte", 1),
                    ),
                    _connector="OR",
                ),
                name="attempt_running_algorithm",
            ),
        ),
    ]
