# Generated by Django 5.2.17 on 2026-10-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("athletes", "0003_submitted_baseline_delete_guard"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="baselineassessment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("height_cm__isnull", True),
                    models.Q(("height_cm__gte", 50), ("height_cm__lte", 250)),
                    _connector="OR",
                ),
                name="baseline_height_bound",
            ),
        ),
        migrations.AddConstraint(
            model_name="baselineassessment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("weight_kg__isnull", True),
                    models.Q(("weight_kg__gte", 20), ("weight_kg__lte", 400)),
                    _connector="OR",
                ),
                name="baseline_weight_bound",
            ),
        ),
        migrations.AddConstraint(
            model_name="baselineassessment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("waist_cm__isnull", True),
                    models.Q(("waist_cm__gte", 20), ("waist_cm__lte", 250)),
                    _connector="OR",
                ),
                name="baseline_waist_bound",
            ),
        ),
        migrations.AddConstraint(
            model_name="baselineassessment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sleep_hours__isnull", True),
                    models.Q(("sleep_hours__gte", 0), ("sleep_hours__lte", 24)),
                    _connector="OR",
                ),
                name="baseline_sleep_bound",
            ),
        ),
        migrations.AddConstraint(
            model_name="baselineassessment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("energy__isnull", True),
                    models.Q(("energy__gte", 1), ("energy__lte", 10)),
                    _connector="OR",
                ),
                name="baseline_energy_bound",
            ),
        ),
        migrations.AddConstraint(
            model_name="baselineassessment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("meals_per_day__isnull", True),
                    ("meals_per_day__lte", 12),
                    _connector="OR",
                ),
                name="baseline_meals_bound",
            ),
        ),
        migrations.AddConstraint(
            model_name="baselineassessment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("training_experience_months__isnull", True),
                    ("training_experience_months__lte", 1200),
                    _connector="OR",
                ),
                name="baseline_experience_month_bound",
            ),
        ),
        migrations.AddConstraint(
            model_name="baselineassessment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("experience__in", ["", "beginner", "intermediate", "advanced"])
                ),
                name="baseline_experience_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="baselineassessment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("lifestyle__in", ["", "sedentary", "mixed", "active"])
                ),
                name="baseline_lifestyle_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="baselineassessment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("hydration_habit__in", ["", "low", "regular", "unknown"])
                ),
                name="baseline_hydration_kind",
            ),
        ),
    ]
