# Generated by Django 5.2.17 on 2026-10-07 22:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("athletes", "0004_bounded_metadata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="profilecommandreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "command__in",
                        [
                            "profile.create",
                            "baseline.begin",
                            "baseline.save_step",
                            "baseline.submit",
                            "baseline.correct",
                            "baseline.clear",
                        ],
                    )
                ),
                name="athletes_receipt_command",
            ),
        ),
        migrations.AddConstraint(
            model_name="profilecommandreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(("request_hash__regex", "^[0-9a-f]{64}$")),
                name="athletes_receipt_hash",
            ),
        ),
    ]
