# Generated by Django 5.2.17 on 2026-10-07 22:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("athletes", "0006_baseline_json_contract"),
    ]

    operations = [
        migrations.AddField(
            model_name="baselineassessment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="profilecommandreceipt",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
