# Generated by Django 5.2.17 on 2026-10-08 05:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("athletes", "0009_ownership_anchors"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="profilecommandreceipt",
            name="athletes_receipt_command",
        ),
        migrations.AddConstraint(
            model_name="athleteprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "onboarding_step__in",
                        [
                            "basics",
                            "goals",
                            "experience",
                            "availability",
                            "facilities",
                            "context",
                            "habits",
                            "measures",
                            "review",
                        ],
                    )
                ),
                name="athlete_onboarding_step",
            ),
        ),
        migrations.AddConstraint(
            model_name="profilecommandreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "command__in",
                        [
                            "profile.create",
                            "baseline.begin",
                            "baseline.save_step",
                            "baseline.submit",
                            "baseline.correct",
                            "baseline.clear",
                            "baseline.grant_storage",
                            "baseline.revoke_storage",
                        ],
                    )
                ),
                name="athletes_receipt_command",
            ),
        ),
    ]
